apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: anurag-saran-poi-map-app-dev
  annotations:
    argocd/app-name: anurag-saran-poi-map-app-dev
    backstage.io/kubernetes-id: anurag-saran-poi-map-app
    backstage.io/kubernetes-namespace: anurag-saran
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhdh-gh/anurag-saran-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.rosa-x4jc7.l07n.p1.openshiftapps.com/dev-pipelines/ns/anurag-saran/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.rosa-x4jc7.l07n.p1.openshiftapps.com/k8s/ns/anurag-saran/deployments/anurag-saran-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.rosa-x4jc7.l07n.p1.openshiftapps.com/#https://github.com/rhdh-gh/anurag-saran-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://anurag-saran-poi-map-app-anurag-saran.apps.rosa-x4jc7.l07n.p1.openshiftapps.com
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/anurag-saran"
  system: workshop-system-anurag-saran
  consumesApis:
    - gateway-api-anurag-saran
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-anurag-saran
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/anurag-saran"
